refactor(root): rename repository to dashboard-components
GenSpectrum/dashboard-components pull request #301
Opened 2024-06-20 09:05 UTC by JonasKellerer

### Summary

Changes all files with old repo name to new repo name

### Screenshot

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

2024-06-24 12:09 UTC, fengelniederhammer requested changes
The changelog also requires a couple of changes in the links there... :)

2024-06-24 12:09 UTC, fengelniederhammer commented on components/src/web-components/input/gs-date-range-selector.tsx
> +     * Visit https://genspectrum.github.io/dashboards-components/?path=/docs/components-size-of-components--docs for more information.
```suggestion
     * Visit https://genspectrum.github.io/dashboard-components/?path=/docs/components-size-of-components--docs for more information.
```

(also for the links in the other files)

2024-06-24 17:58 UTC, JonasKellerer commented on components/src/web-components/input/gs-date-range-selector.tsx
> +     * Visit https://genspectrum.github.io/dashboards-components/?path=/docs/components-size-of-components--docs for more information.
Ah, the second renaming... Good catch.

2024-06-25 06:56 UTC, fengelniederhammer approved these changes

2024-06-25 07:02 UTC, merged