feat(components): initial mutations over time component
GenSpectrum/dashboard-components pull request #358
Opened 2024-07-18 11:43 UTC by JonasKellerer

resolves #59

### Summary

Adds a new component, which shows the mutations over time, similar to covSpectrum. 
Currently missing are the tooltips and the selector for the color scale. They will be done in #353 and #354.

### Screenshot

![grafik](https://github.com/user-attachments/assets/46a00d2f-5bbb-4ec9-ba4c-6c88ff2cb3e4)

### PR Checklist

- [x] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2024-07-18 11:44 UTC, JonasKellerer commented
This PR is missing a test for the queryMutationOverTime function, which will be added.

2024-07-18 12:33 UTC, chaoran-chen reviewed
Amazing!

I briefly tested it and found a few small issues:

- The granularity switch doesn't work for me.
- Let's better call it "mutation**s** over time", not "mutation" (plural!)
- The code example in storybooks uses "<gs-mutations" without "-over-time"

2024-07-19 09:13 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/mutations-over-time.tsx
> +                        return [{ value: 1 }, { value: 2 }];
There is now an issue #362

2024-07-19 09:14 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/mutations-over-time.tsx
> +                    filename='mutation-over-time.csv'
This will be done in #362

2024-07-19 09:14 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-mutations-over-time.stories.ts
> +    headline="Mutations over time"
Was removed during rebase.

2024-07-19 09:27 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-mutations-over-time.tsx
> +type ViewsMatches = Expect<Equals<typeof MutationsOverTimeComponent.prototype.views, View[]>>;
I changed it here, but added another ticket for all the other components, which have the same style:  #363

2024-07-19 12:00 UTC, fengelniederhammer requested changes
Some minor things. In general it looks good :+1:

2024-07-19 12:01 UTC, fengelniederhammer commented
It would also be good to link the issue in the commit message (either appending the issue to the header or by using `closes #` or `Refs: #` in the footer.

2024-07-19 12:04 UTC, fengelniederhammer commented on components/vitest.setup.ts
> +            http.post(substitutionsOrDeletionsEndpoint(DUMMY_LAPIS_URL, sequenceType), async ({ request }) => {
Probably `resolver` could even use `any` instead of the generics.

2024-07-19 12:12 UTC, JonasKellerer commented on components/src/query/queryMutationsOverTime.spec.ts
> +        ]);
Yeah. I was also wandering about it. My reasoning for not sorting it is that a regular map also does not sort it. So the user is responsible for sorting. In this case the sorting of the date keys in the grid component.

2024-07-22 07:01 UTC, fengelniederhammer approved these changes
LGTM

* Do we still need to implement a limit on how many mutations we show in the grid at a time?
* Do we need the intermediate commit that sets the minProportion? AFAIK it only affects this (new) component anyway.

2024-07-22 08:05 UTC, JonasKellerer commented
As discussed: we added a new ticket #367 to limit the number of shown mutations/dates. For now we keep the component as is.

I rebased the PR, so we get rid of the extra commit.

2024-07-22 08:12 UTC, merged