feat(components): add color scale selector to mutations over time #354
GenSpectrum/dashboard-components pull request #378
Opened 2024-07-23 13:08 UTC by JonasKellerer

resolves #354

### Summary

Adds a color scale selector to the mutation over time component. The scale provides a method to select the maximum and minimum value for the color scale values. This changes the background colour as well as the text color.

As a side product: centers the `MinMaxRangeSlider` inside its div so it can be aligned with the coloured rectangles.

### Screenshot

![grafik](https://github.com/user-attachments/assets/7feb7009-f5e1-429b-bd68-6d39e3ce01ec)

### PR Checklist

- ~~[] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

2024-07-23 13:54 UTC, fengelniederhammer requested changes
Actually looks good :+1:

2024-07-23 13:54 UTC, fengelniederhammer commented on components/src/preact/components/color-scale-selector.tsx
> +            </div>
It would actually be nice if users could type a value into this field.

2024-07-23 13:54 UTC, fengelniederhammer commented on components/tests/snapshots.spec.ts-snapshots/Mutations-over-time-Story-visualization-mutations-over-time--default-should-match-screenshot-1-chromium-linux.png
Please regenerate the screenshots (now that the download button is merged)

2024-07-23 13:54 UTC, fengelniederhammer commented on components/src/preact/components/color-scale-selector.stories.tsx
> +        await step('Move min silder to 20%', async () => {
```suggestion
        await step('Move min slider to 20%', async () => {
```

2024-07-23 13:54 UTC, fengelniederhammer commented on components/src/preact/components/color-scale-selector.stories.tsx
> +        await step('Move max silder to 80%', async () => {
```suggestion
        await step('Move max slider to 80%', async () => {
```

2024-07-25 09:24 UTC, JonasKellerer commented on components/src/preact/components/color-scale-selector.tsx
> +            </div>
As discussed, we leave it as it is. In the future we also want the feature, to select the min and max colour: #390

2024-07-25 09:37 UTC, fengelniederhammer approved these changes

2024-07-25 09:51 UTC, merged