feat(components): add info texts for four components
GenSpectrum/dashboard-components pull request #397
Opened 2024-07-25 15:57 UTC by chaoran-chen

...namely: Aggregate, Mutations, NumberSequencesOverTime, and PrevalenceOverTime

I'll document mutations over time and mutation comparison in a later PR.

### PR Checklist

- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~

2024-07-29 08:20 UTC, fengelniederhammer requested changes
I'll make suggestions and fix the tests.

2024-07-29 08:20 UTC, fengelniederhammer commented on components/src/preact/aggregatedData/aggregate.tsx
> +                    This table shows the number and proportion of sequences stratified by the following fields:{' '}
Do we need to explain what the proportion is relative to?

2024-07-29 08:20 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
> +            <InfoLink href='https://www.genome.gov/genetics-glossary/Deletion'>deletions</InfoLink>, and{' '}
```suggestion
            <InfoLink href='https://www.genome.gov/genetics-glossary/Deletion'>deletions</InfoLink> and{' '}
```

2024-07-29 08:20 UTC, fengelniederhammer commented on components/src/preact/numberSequencesOverTime/number-sequences-over-time.tsx
> +            {smoothingWindow > 0 ? `, smoothed using a ${smoothingWindow}-${granularity} sliding window` : ''}.
```suggestion
            {smoothingWindow > 0 && `, smoothed using a ${smoothingWindow}-${granularity} sliding window`}.
```

2024-07-29 08:20 UTC, fengelniederhammer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                {smoothingWindow > 0 ? `, smoothed using a ${smoothingWindow}-${granularity} sliding window` : ''}.
```suggestion
                {smoothingWindow > 0 && `, smoothed using a ${smoothingWindow}-${granularity} sliding window`}.
```

2024-07-29 08:20 UTC, fengelniederhammer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                This presents the proportion of a variant per <b>{granularity}</b>
I think we should explain that there is a baseline filter that we compare against here.

2024-07-29 08:32 UTC, fengelniederhammer commented on components/src/preact/aggregatedData/aggregate.tsx
Reminder: Squash before merge

2024-07-29 08:32 UTC, fengelniederhammer commented
I tried to clarify some descriptions a little.

2024-07-29 12:29 UTC, chaoran-chen commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                This presents the proportion of a variant per <b>{granularity}</b>
Do you have a suggestion on how to explain it? I find it hard to come up with a general phrasing (since the baseline can be defined in very different ways).

2024-07-29 12:30 UTC, chaoran-chen commented on components/src/preact/aggregatedData/aggregate.tsx
> +                    This table shows the number and proportion of sequences stratified by the following fields:{' '}
Same as below: because the baseline/denominator can be defined very flexibly, I find it difficult to come up with a good phrasing. Do you have an idea?

2024-07-29 12:42 UTC, fengelniederhammer commented on components/src/preact/aggregatedData/aggregate.tsx
> +                    This table shows the number and proportion of sequences stratified by the following fields:{' '}
"The proportion is calculated with respect to the total count within the filtered dataset."

2024-07-29 12:42 UTC, fengelniederhammer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                This presents the proportion of a variant per <b>{granularity}</b>
```html
            <InfoParagraph>
                This presents the proportion of one or more variants per <b>{granularity}</b>
                {smoothingWindow > 0 && `, smoothed using a ${smoothingWindow}-${granularity} sliding window`}. The
                proportion is calculated as the number of sequences of the variant(s) divided by the total number of
                sequences of a reference variant.
            </InfoParagraph>
```

2024-07-29 12:57 UTC, chaoran-chen commented on components/src/preact/aggregatedData/aggregate.tsx
> +                    This table shows the number and proportion of sequences stratified by the following fields:{' '}
"the filtered dataset" is very unspecific but once we show the exact code underlying a component (as we introduced for the prevalence over time plot in #404, we can refer to it). For now, I think adding just your sentence is good enough.

2024-07-29 13:47 UTC, JonasKellerer requested changes
Nice. Thank you. The info text is very helpful.

Do we also mention how the confidence interval is calculated? This would be the case for all display components.

2024-07-29 13:47 UTC, JonasKellerer commented on components/src/preact/mutations/mutations.tsx
> +            <b>Example:</b> If we look at nucleotide mutations at position 5 where the reference has a T: if there are
```suggestion
            <b>Example:</b> Assume we look at nucleotide mutations at position 5 where the reference has a T and there are
```
Two chained ifs. And I would put some of the text in bullet points like this:

Assume we look at nucleotide mutations at position 5 where the reference has a T and there are 10 sequences in total:

- 3 sequences have a C
- 2 sequences have a T
- 1 sequence has a G
- 3 sequences have an N
- 1 sequence has a Y (which means T or C)
 
then the proportion ...

2024-07-29 13:47 UTC, JonasKellerer commented on components/src/preact/mutations/mutations.tsx
> +            <b>Example:</b> If we look at nucleotide mutations at position 5 where the reference has a T: if there are
I would also add a link to the ambiguous symbols.

2024-07-29 13:47 UTC, JonasKellerer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                        In the bubble chart, the size of the bubble scales with the total number of available sequences
```suggestion
                        The size of the bubble scales with the total number of available sequences
```

2024-07-29 13:47 UTC, JonasKellerer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                This presents the proportion of a variant per <b>{granularity}</b>
I like the bit about the smoothing window. The user can look at the code from #404 to see the lapis filter. But I think the user has no knowledge of the smoothing in that case. They see only a number, which has no context.

2024-07-29 13:47 UTC, JonasKellerer commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                    <InfoParagraph>
I think we do not mention, that in the line and bubble graph we filter for null values, and we show them in the bar and table. Maybe we can add something like

"If there are sequences, which have no assigned date, they are shown in the bar and table view."

2024-07-29 14:17 UTC, fengelniederhammer commented on components/src/preact/mutations/mutations.tsx
> +            <b>Example:</b> If we look at nucleotide mutations at position 5 where the reference has a T: if there are
Which link? Is it important to have this link here? The ambiguous symbols don't show up in the table/grid, do they?

2024-07-29 14:44 UTC, chaoran-chen commented on components/src/preact/prevalenceOverTime/prevalence-over-time.tsx
> +                This presents the proportion of a variant per <b>{granularity}</b>
Yes, I would keep the bit about the smoothing window as it is. So, together, it would be:

```
This presents the proportion of one or more variants per <b>{granularity}</b>
{smoothingWindow > 0 && `, smoothed using a ${smoothingWindow}-${granularity} sliding window`}. The
proportion is calculated as the number of sequences of the variant(s) divided by the total number 
of sequences that match the denominatorFilter (see below).
```

2024-07-30 07:17 UTC, JonasKellerer commented on components/src/preact/mutations/mutations.tsx
> +            <b>Example:</b> If we look at nucleotide mutations at position 5 where the reference has a T: if there are
I dont know which link. From a short google search I came up with: https://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html (Dont know if this is a good way to present this). I just thought it would be nice to have the reference here. Or a link to our doku page. 
But your right, they dont show in the grid.

2024-07-30 11:31 UTC, JonasKellerer commented on components/src/preact/mutations/mutations.tsx
> +            <b>Example:</b> Assume we look at nucleotide mutations at position 5 where the reference has a T and if
```suggestion
            <b>Example:</b> Assume we look at nucleotide mutations at position 5 where the reference has a T and assume
```
I think assume would be better here. If seems wrong.

2024-07-30 12:35 UTC, JonasKellerer approved these changes

2024-07-30 12:35 UTC, merged