perf(components): speed up mutations over time proportion filter  #388
GenSpectrum/dashboard-components pull request #422
Opened 2024-07-30 13:06 UTC by JonasKellerer

resolves #388

### Summary

This introduces an interface of the 2dMap. On the interface we can delete rows, by deleting only the keys of the map. The underlying data is not touched. This increases the speed because we do not need to copy the data for each filter step.

The speed now seem comparable to covSpectrum. There the calculation is hidden by showing a spinner. An idea, to create a similar user experience, is to decouple the display of the mutation proportion from the filtering process. This is targeted by this ticket: #421 

### Screenshot

### PR Checklist

- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~

2024-07-30 15:20 UTC, fengelniederhammer requested changes
The performance is indeed a lot better, but probably still not sufficient :+1:

2024-07-30 15:20 UTC, fengelniederhammer commented on components/src/utils/Map2d.ts
> +    readonly baseMap: Map2d<Key1, Key2, Value> = new Map2d();
```suggestion
    readonly baseMap: Map2dInterface<Key1, Key2, Value>;
```

2024-07-30 15:20 UTC, fengelniederhammer commented on components/src/utils/Map2d.ts
> +        return Array.from(this.keysSecondAxis.keys()).map((key) => row.get(key) ?? fillEmptyWith);
```suggestion
        return this.baseMap.getRow(key, fillEmptyWith);
```

2024-07-30 15:20 UTC, fengelniederhammer commented on components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts
> -    const filteredData = data.copy();
Let's also delete the copy method?

2024-07-30 15:20 UTC, fengelniederhammer commented on components/src/utils/Map2d.ts
> +export class Map2dView<Key1 extends object | string, Key2 extends object | string, Value>
At least some basic unit test would be good.

2024-07-31 06:18 UTC, JonasKellerer commented on components/src/utils/Map2d.ts
> +export interface Map2dInterface<Key1, Key2, Value> {
I tried going with `Map2dDataContainer` but I'm not very happy with it.

2024-07-31 06:20 UTC, JonasKellerer commented on components/src/utils/Map2d.ts
> +        }
For this to work, I needed to add the `serializeFirstAxis` and `serializeSecondAxis` to the interface, which is fine for our purpose. I also added, the set method, since we renamed the interface and a map should have a set function. For the view it throws an error.

2024-07-31 06:52 UTC, fengelniederhammer commented on components/src/utils/Map2d.ts
> +export interface Map2dInterface<Key1, Key2, Value> {
`BaseMap2d`? `ConcreteMap2d`?

2024-07-31 07:03 UTC, JonasKellerer commented on components/src/utils/Map2d.ts
> +export interface Map2dInterface<Key1, Key2, Value> {
I now went for `Map2dBase`

2024-07-31 11:31 UTC, fengelniederhammer approved these changes

2024-07-31 11:31 UTC, fengelniederhammer commented on components/src/utils/map2d.spec.ts
> +    it('should return an epmty array when the row does not exist', () => {
```suggestion
    it('should return an empty array when the row does not exist', () => {
```

2024-07-31 11:55 UTC, merged