478 improve performance of mutation over time
GenSpectrum/dashboard-components pull request #483
Opened 2024-11-04 09:47 UTC by JonasKellerer

resolves #478 

### Summary

The main change is this PR, is the introduction of web workers for the calculation of the mutations over time. This allows for parallel computation, which is not available otherwise in js.

You can not pass classes with functions to (and from) the web worker. Therefore, I introduced an interface for the temporal and mutation class, which only contains the data of the respective class. The same issue occurred for the `Map2d` class, which now can export/import the underlying data. 

Testing of a component using the web worker is done through a mock. The mock is enabled using special import directives. This was necessary, since the current mocking approach only allows to mock calls on the same thread. 

In this PR also includes
  - a fix, where the initial mutation call (which calculates all mutations in the time window) did not include the same dates as the single mutation calls for each time window. 
  - a performance improvement in the filtering step of the mutations. Now the filtering is done only on the overall mutations, and the map is then updated.
  - a minor fix, where the tag of mutation over time component is not correctly exported 

The playwright snapshot tests needed to be updated. The values changed, due to the fix of the overall mutation call and because we call a pango lineage with asterix (JN.1*). Since our last snapshot of the data, there were some other lineages assigned as children of that lineage, which changes the proportion.

### Screenshot

### PR Checklist

- [x] All necessary documentation has been adapted.
- [x] The implemented feature is covered by an appropriate test.

2024-11-04 14:18 UTC, fengelniederhammer requested changes
Looks good! Just a couple of minor things.

2024-11-04 14:18 UTC, fengelniederhammer commented on examples/React/src/App.tsx
> +                lapisFilter='{ "pangoLineage": "JN.1*", "dateFrom": "2024-01-15", "dateTo": "2024-07-10" }'
```suggestion
                lapisFilter={JSON.stringify(numerator.lapisFilter)}
```

(and maybe we can change the default pango lineage to `B.1.1.7*` to get more data)

2024-11-05 10:02 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/mutations-over-time.tsx
> +        return dates.reduce(
The sorting is now done in the worker. So what we return is already sorted.

2024-11-05 10:15 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts
> +        return outsideProportionInterval || notDisplayedSegment || notDisplayedMutationType;
I changed it to make it easier to read. 

I just learned: js has in principle short-circuit logic, meaning that it will not evaluate a boolean expression further if one of the entries already resulting in the output. So something like 
```firstBoolean() || secondBoolean() || thirdBoolean()```
will not evaluate `secondBoolean()` or `thirdBoolean()` when `firstBoolean()` already is true.
However, this is not the case when we store the values in a const, since js is not compiled like c++, where this would also use the short circuit logic.

2024-11-05 10:55 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/mutationOverTimeWorker.ts
> +self.onmessage = async function (event: MessageEvent<MutationOverTimeQuery>) {
As discussed: we will take a look at this in #485

2024-11-05 11:09 UTC, fengelniederhammer commented on components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts
> +        return outsideProportionInterval || notDisplayedSegment || notDisplayedMutationType;
I also looked at the result of this code after building it. It's actually quite interesting what happens. In the original version, the bundler did not inline the variables. With early returns, they get partially inlined and transformed to something that still allows short-circuit.

2024-11-05 12:31 UTC, JonasKellerer commented on components/src/preact/webWorkers/useWebWorker.ts
> +    }, [messageToWorker]);
Yes and no. The worker changes between renderings, due to line 86 in `mutations-over-time.tsx`. I tried to put the worker inside a useMemo, or a useRef. However, this way the component reloads indefinitely. I could not make it work otherwise. I would propose to create a new ticket to investigate this behavior, but use it like it is now. The web worker will only be started again when the component rerenders. This should only be the case on page load.

2024-11-05 12:32 UTC, JonasKellerer commented on components/src/preact/webWorkers/useWebWorker.ts
> +    useEffect(() => {
I added it. The terminate function should be called, when our component is removed from the dom. So, when there is still a calculation running while the user changes the screen, then this calculation should be stopped.

2024-11-05 13:50 UTC, JonasKellerer commented on components/src/preact/mutationsOverTime/getFilteredMutationsOverTimeData.ts
> +        const notDisplayedSegment = displayedSegments.some(
This is a larger task, so I created a ticket for it: #486

2024-11-06 07:30 UTC, fengelniederhammer approved these changes
LGTM

2024-11-06 07:30 UTC, fengelniederhammer commented on components/src/preact/mutationsOverTime/getFilteredMutationsOverTime.spec.ts
> +        ]);
I like this solution :)

2024-11-06 07:30 UTC, fengelniederhammer commented on components/src/utils/mutations.ts
>      readonly type: MutationType;
```suggestion
export interface MutationClass extends Mutation {
```
Doesn't that do the job?

2024-11-06 08:12 UTC, merged