Use a dropdown to select mutations from
GenSpectrum/dashboard-components pull request #498
Opened 2024-11-12 16:23 UTC by anna-parker

resolves #

### Summary

### Screenshot

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2024-11-13 13:25 UTC, fengelniederhammer requested changes
As discussed: I think it would be simpler and equally good if we don't try to implement another `AsyncSelect`. I'd propose to have a dedicated mutation input field that doesn't aim to be general purpose, but is just a text input with a single "autocomplete option", if the value is a valid mutation.

IMO keyboard navigation is a must. There should be some way to hit "enter" and submit the muation. I'm not sure how a good solution would look like. `<datalist>` doesn't work, because it doesn't have events by itself. Instead the corresponding input element gets `input` event -> you can't differentiate whether an option was selected or whether something was typed in the input element.

(Most of my other comments are probably irrelevant now)

2024-11-13 16:40 UTC, anna-parker commented on components/src/preact/mutationFilter/asyncselect.tsx
> +        <div className={className} style={{ position: 'relative' }} ref={wrapperRef} tabIndex={-1}>
done :-)

2024-11-13 16:40 UTC, anna-parker commented on components/src/preact/mutationFilter/asyncselect.tsx
> +        if (inputValue) loadAsyncSearchOptions();
done :-)

2024-11-13 16:40 UTC, anna-parker commented on components/src/preact/mutationFilter/asyncselect.tsx
done :-)

2024-11-13 16:48 UTC, anna-parker commented
@fengelniederhammer I now modified the async-select component to treat users clicking enter the same as clicking on an item. Should I leave the async-select component as is now and just add some more general tests for it? Or would you still prefer I try to make to his one component that is specifically for selecting mutations?

2024-11-14 09:04 UTC, anna-parker commented on components/src/preact/mutationFilter/async-select.tsx
> +                onInput={(e: Event) => onInputChange((e.target as HTMLInputElement).value)}
replace with onKeyDown()

2024-11-14 09:30 UTC, anna-parker commented on components/src/preact/mutationFilter/async-select.tsx
> +                onInput={(e: Event) => onInputChange((e.target as HTMLInputElement).value)}
TODO: add a test that enter works as planned

2024-11-14 17:16 UTC, anna-parker commented
I think it is easiest to close this PR as I added more features and tests in https://github.com/GenSpectrum/dashboard-components/pull/500 and it includes this functionality.

2024-11-14 17:16 UTC, closed without merging