Allow multiple mutations in query
GenSpectrum/dashboard-components pull request #500
Opened 2024-11-13 09:27 UTC by anna-parker

resolves #

### Summary

### Screenshot

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [ ] The implemented feature is covered by an appropriate test.

2024-11-14 18:00 UTC, fengelniederhammer requested changes
The behavior is slightly weird: When I type "a,2", then 2 gets accepted without any popup and "a" stays in the input field. I don't think it's terribly bad, it's just a bit weird.

Could you please clean up your code a bit? There are still some unnecessary steps from inlining the asny select component.
Also `MutationFilterInner` is too big for my taste (almost 200 lines of code). Maybe we can extract something to make it easier to digest.

And please rewrite your commit messages to something that is meaningful to users:
* Some of your commits seem to be internal refactoring, they should not be in the changelog.
* Entries in the changelog should contain references to the issue that they solve. You can add `resolves #xyz` to the commit message footer.

2024-11-15 06:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> -const SelectedMutationDisplay: FunctionComponent<{
Why don't we actually keep the old implementation here? Was there something wrong with it?

2024-11-15 06:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                )}
Thinking about it: It probably makes sense to split out this part (the `<input>` and it's attached "option" into a separate subcomponent. That would disentangle the code and encapsulate the "option" feature, so that this top-level component doesn't need to know about it.

2024-11-15 08:33 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        } else if (change.action === 'remove-value' || change.action === 'pop-value') {
No - I will remove it :-)

2024-11-15 08:36 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        if (!filterRef.current?.contains(event.relatedTarget as Node)) {
Otherwise blur will fire every time we click on an option as handlBlur is currently always called when we exit the input field.

2024-11-15 08:38 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        return Promise.resolve(parseAndValidateMutation(newValue, referenceGenome));
I originally didn't add the Promise here, however without it the option that is shown in the dropdown is out of sync with the input - adding await in `handleInputChange` resolved the problem. As I'm not a typescipt expert maybe there is a better way to do this

2024-11-15 08:40 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        return Promise.resolve(parseAndValidateMutation(newValue, referenceGenome));
Removing the promise and the await could maybe solve it? It seems quite weird that we need to wrap sync code artificially in promises.

2024-11-15 08:56 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    const [menuVisible, setMenuVisible] = useState(false);
Ah good catch!

2024-11-15 09:38 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        return Promise.resolve(parseAndValidateMutation(newValue, referenceGenome));
Oh odd it works without... must have been another issue, thanks for finding this!

2024-11-15 10:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    const inputRef = useRef<HTMLInputElement>(null);
I think we don't need this, do we?

2024-11-15 10:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                <input
I think this could use a little margin. If you look closely, it overlaps with the surrounding frame (top left corner):

![grafik](https://github.com/user-attachments/assets/9b29b0f4-0866-44bc-92ee-e6a8f4c01ad8)

2024-11-15 10:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                new CustomEvent<SelectedMutationFilterStrings>('gs-mutation-filter-on-blur', {
As discussed: Let's remove this event - it doesn't really make sense.

Users should be able to listen to either `-changed` events only or `-on-blur` events only. When the user deletes a mutation, no `-on-blur` event is fired (also currently on main). This is a conceptual issue -> IMO it's better to remove it completely, as it doesn't work as intended (intention: group all changes and only then fire an event).

2024-11-15 10:55 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    };
Let's inline this function? It doesn't really provide benefit, it just obfuscates (IMO)

2024-11-15 12:08 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        if (!filterRef.current?.contains(event.relatedTarget as Node)) {
Resolving as we will now remove the fire on blur dispatch event

2024-11-15 12:49 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                )}
As the function is now much smaller I think I will leave this as is - but let me know if you would still like me to do this

2024-11-15 14:21 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                )}
I would still prefer to have it split out to a separate component (for the sake of cleaner code).

2024-11-15 14:56 UTC, fengelniederhammer requested changes
The current `resolves #x, #y` in the commit message doesn't work. I think you can simply make it two:
```
resolves #x
resolves #y
```

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            <div className='relative w-full p-1' tabIndex={-1}>
Do we need the tabIndex?

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.stories.tsx
> +            expect(inputField(canvas)).toHaveValue('error_insX');
Those expects need to be awaited:
```suggestion
            await expect(firstMutationButtons).toHaveLength(1);
            const secondValidMutationButtons = canvas.queryAllByText('A234T', { exact: false });
            await expect(secondValidMutationButtons).toHaveLength(1);
            await expect(inputField(canvas)).toHaveValue('error_insX');
```

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.stories.tsx
> +    expect(options).toHaveLength(0);
```suggestion
    await expect(options).toHaveLength(0);
```

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.stories.tsx
> +        await step('Move outside of input', async () => {
The step title doesn't really fit IMO.

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +};
Let's move those two down to where they are used?

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    const handleInputChange = async (newValue: string) => {
```suggestion
    const handleInputChange = (newValue: string) => {
```

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                    onFocus={() => parseAndValidateMutation(inputValue, referenceGenome)}
Why do we need `onFocus` here?

2024-11-15 14:56 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            onClick={() => handleRemoveValue(filter)}
I think it would be better to have a dedicated button to remove the mutation. I tried to copy a mutation, but it didn't let me do it, instead the mutation was always deleted.

2024-11-18 12:38 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                    onFocus={() => parseAndValidateMutation(inputValue, referenceGenome)}
Yeah this was a bit broken before, but it is needed because after blur we close the options dropdown by setting options to null. If you then click back on the input it shows no options because this is set to null, so options needs to be recalculated from the inputValue each time input comes back into focus. I modified this slightly and it works again :-)

2024-11-18 12:39 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            <div className='relative w-full p-1' tabIndex={-1}>
I actually need the tabIndex for making sure blur is not called just by selecting options from the dropdown - I moved it to the subfunction :-)

2024-11-18 12:39 UTC, anna-parker commented on components/src/web-components/input/gs-mutation-filter.stories.ts
> +            );
Ah I forgot about this, maybe you can actually help me with it as I cannot get this test function to work I just get shadow dom errors but the text is clearly there

2024-11-18 17:50 UTC, anna-parker commented on components/src/web-components/input/gs-mutation-filter.stories.ts
> +            );
Ah I fixed it now :-)

2024-11-19 09:03 UTC, fengelniederhammer requested changes
I think we should at least do the separate delete button, otherwise it looks good :)

2024-11-19 09:03 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +        <button
In conjunction with the other change (dedicated delete button), we don't need a button here.
```suggestion
        <span
```

2024-11-19 09:14 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +            {mutationFilter.value.toString()} &times;
Good idea!

2024-11-19 12:30 UTC, fengelniederhammer approved these changes
Looks good, just a few final things :)

2024-11-19 12:30 UTC, fengelniederhammer commented on components/src/preact/mutationFilter/mutation-filter.stories.tsx
> +            await expect(secondValidMutationButtons).toHaveLength(1);
```suggestion
            await expect(canvas.queryByText('A123T')).toBeVisible();
            await expect(canvas.queryByText('A234T')).toBeVisible();
```

2024-11-19 12:56 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    };
Oh no! When I initially wrote it I made sure it would deduplicate values - I must have lost that feature in one of the refactors - I will add it back

2024-11-19 12:58 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +                name={mutationFilter.value.toString()}
That way you can select the buttons in the tests to delete them - I think its a good name, it should be unique when I fix the duplication bug

2024-11-19 13:02 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.stories.tsx
> +            await waitFor(() => fireEvent.click(firstMutationDeleteButton));
Weird locally it is green for me and when I change to this it is red...

2024-11-19 13:44 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    };
Its fixed again :-)

2024-11-19 13:45 UTC, anna-parker commented on components/src/preact/mutationFilter/mutation-filter.tsx
> +    };
Thanks for flagging this!

2024-11-19 13:50 UTC, merged