feat(components): add mutation over time plot for wastewater / WISE
GenSpectrum/dashboard-components pull request #504
Opened 2024-11-14 14:56 UTC by chaoran-chen

2024-11-14 14:58 UTC, chaoran-chen commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +    // TODO
Don't forget

2024-11-14 14:58 UTC, chaoran-chen commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +            <InfoParagraph>TODO: Ask for text</InfoParagraph>
Don't forget

2025-01-19 23:24 UTC, chaoran-chen commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +    // TODO
Can be done later.

2025-01-21 07:53 UTC, JonasKellerer requested changes
Nice work. I am looking forward to the finished component. 

The dates in the table are not sorted. So for Lugano the second column is 17.11.2024 and the last column 16.11.2024. I think this is also the case for other locations. 

On the Laupen and Chur tab, there is only one column. In this column there are many "NoData" entries, which I find confusing. I think we should omit the rows where there is no data for all times.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-wastewater-mutations-over-time.stories.ts
> +    title: 'Visualization/Wastewater mutations over time',
```suggestion
    title: 'Wastewater/Mutations over time',
```
I would put the specific wastwater components in a different folder, so it is clear, that they are not used for "normal" people.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-wastewater-mutations-over-time.stories.ts
When I switch the control of sequence type to "amino acid" there is no data for all locations. It would be nice to see in the story, that the entries for at least one location works.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-wastewater-mutations-over-time.tsx
> +     * "nucleotide" or "amino acid"
This docs could tell more, but not blocking for me.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/web-components/visualization/gs-wastewater-mutations-over-time.tsx
> +}
We don't have the type checks here, that we have for the other components.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/lapisApi/lapisTypes.ts
> +export const detailsItem = z.object({}).catchall(z.union([z.string(), z.number(), z.null()]));
I think `z.union([z.string(), z.number(), z.null()])` is also used for the aggregatedItem. We could extract the type here, since it should be the same entries.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/preact/components/tabs.tsx
> +        <div className='flex flex-row flex-wrap'>
I think we should change our design of the tabs a little, when we want to do this. (But this does not need to be done in this PR. When the tabs are on different rows, it would be nice to have an indicator/border around the tabs, to know that they are different tabs. Similar to the highlight on hover. 

![grafik](https://github.com/user-attachments/assets/77c1006b-197e-4dc3-9c2a-db540c8ddf6b)

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +                mutation.proportion !== null ? { proportion: mutation.proportion, count: NaN, totalCount: NaN } : null,
Why is the count and the totalCount a "NaN" should it not be a "null" or "undefined". NaN suggests to me that it is inf or something devided by zero.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +    const mutationOverTimeDataPerLocation = [...locationMap.entries()].map(([location, data]) => ({ location, data }));
For me this should be in queryWasteWaterMutationsOverTime, so we can also test it.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +            <InfoHeadline1>Info for mutations over time</InfoHeadline1>
Not neccessary this PR, but a bit more info would be nice. Especially, since it is different from the mutations over time component.

2025-01-21 07:53 UTC, JonasKellerer commented on components/src/query/queryWastewaterMutationsOverTime.ts
> +                : [],
At some point, it would be nice to use zod here to make shure the data is correct.

2025-01-21 08:40 UTC, chaoran-chen commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +            <InfoHeadline1>Info for mutations over time</InfoHeadline1>
I would keep it as this for now and once it's up, I can point to it and ask the wastewater team whether they would like to write something to explain the method and data.

2025-01-21 09:37 UTC, fengelniederhammer commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +            <InfoHeadline1>Info for mutations over time</InfoHeadline1>
I also created #670 to do it later.

2025-01-21 10:22 UTC, fengelniederhammer commented on components/src/preact/components/tabs.tsx
> +        <div className='flex flex-row flex-wrap'>
I added #675

2025-01-21 10:28 UTC, fengelniederhammer commented on components/src/query/queryWastewaterMutationsOverTime.ts
> +                : [],
In the end this comes from LAPIS, which is rather trustworthy. I'm not sure whether it's worth the trouble.

2025-01-21 10:37 UTC, fengelniederhammer commented on components/src/preact/wastewater/mutationsOverTime/wastewater-mutations-over-time.tsx
> +                mutation.proportion !== null ? { proportion: mutation.proportion, count: NaN, totalCount: NaN } : null,
I changed it to `null` to make it more explicit.

2025-01-21 12:10 UTC, fengelniederhammer commented
> On the Laupen and Chur tab, there is only one column. In this column there are many "NoData" entries, which I find confusing. I think we should omit the rows where there is no data for all times.

@chaoran-chen What do you think? Should we hide those rows? IMO it would also be ok to display them, it's a decision of what we want to show.
![grafik](https://github.com/user-attachments/assets/469f041c-b84d-476b-aafe-ab4f5d92971a)

2025-01-21 12:17 UTC, chaoran-chen commented
I don't think that we should hide any rows. If they shouldn't be shown, the data team can just remove the data entry.

2025-01-21 13:21 UTC, merged

2025-01-21 13:24 UTC, anna-parker commented
As this reuses the mutations over time component when I hover over the fields I see proportion and not frequency, although the data is a frequency: 
![image](https://github.com/user-attachments/assets/ea08342d-9461-4653-a1e5-89f4bdcf5308)
can we change this?

2025-01-21 13:27 UTC, anna-parker commented on components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
> + * It relies on a LAPIS instance that has the fields `nucleotideMutationFrequency` and `aminoAcidMutationFrequency`.
it also requires the fields `location` and `date`

2025-01-21 13:34 UTC, fengelniederhammer commented on components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
> + * It relies on a LAPIS instance that has the fields `nucleotideMutationFrequency` and `aminoAcidMutationFrequency`.
As is mentioned in the next two parts of the docs.

2025-01-21 13:35 UTC, fengelniederhammer commented
> I see proportion and not frequency, although the data is a frequency:

What do you mean by frequency?

2025-01-21 14:00 UTC, anna-parker commented on components/src/preact/wastewater/mutationsOverTime/computeWastewaterMutationsOverTimeDataPerLocation.spec.ts
> +                nucleotideMutationFrequency: [
what happens if mutation1 is not in all nucleotideMutationFrequency lists at location1? all the examples have the same nucleotideMutations in the nucleotideMutationFrequency list for the same location but this isn't mentioned in the docs as a requirement

2025-01-21 14:05 UTC, fengelniederhammer commented on components/src/preact/wastewater/mutationsOverTime/computeWastewaterMutationsOverTimeDataPerLocation.spec.ts
> +                nucleotideMutationFrequency: [
Missing values will result in `undefined`, which is handled in the `mutations-over-time-grid`. (It would have probably been good to add that case in a test here)

2025-01-21 14:06 UTC, anna-parker commented on components/src/preact/wastewater/mutationsOverTime/computeWastewaterMutationsOverTimeDataPerLocation.spec.ts
> +                nucleotideMutationFrequency: [
ah great if a mutation is not added for a specific time `null` is added in for that time and the row still exists if the mutation shows up at other time.

2025-01-21 14:06 UTC, anna-parker commented on components/src/web-components/wastewaterVisualization/gs-wastewater-mutations-over-time.tsx
> + * It relies on a LAPIS instance that has the fields `nucleotideMutationFrequency` and `aminoAcidMutationFrequency`.
would be nice to have them together :-)