feat(components): export utils as extra entrypoint
GenSpectrum/dashboard-components pull request #533
Opened 2024-11-20 15:55 UTC by JonasKellerer

BREAKING CHANGE: DateRangeOption and dateRangeOptionPresets now in own sub package

### Summary

When importing our components utility functions (like dateRangeOptionPresets) in a node environment or on the server side of an astro application we get an error, that "HTMLElement not defined". This message occurs, because the lit element class extends HTMLElement. 
To provide users of our package also access to our utility functions, we put them into an own sub-package. They can now be imported through e.g.: `import { dateRangeOptionPresets } from '@genspectrum/dashboard-components/util';`

### Screenshot

### PR Checklist

- [x] All necessary documentation has been adapted.
~~- [ ] The implemented feature is covered by an appropriate test.~~

2024-11-20 16:08 UTC, fengelniederhammer commented on components/package.json
>          ".": {
Let's rename this to `components`, too?

2024-11-20 16:22 UTC, fengelniederhammer requested changes

2024-11-20 16:22 UTC, fengelniederhammer commented on components/vite.release-standalone.config.ts
> +                components: 'dist/components.js',
If we rename that, we also need to adapt the places where this is used (in the README, in the codepen links)

2024-11-21 07:56 UTC, JonasKellerer commented on components/vite.release-standalone.config.ts
> +                components: 'dist/components.js',
I reverted it. So when importing the standalone bundle, one has still to import `dashboard-components.js`

2024-11-21 07:57 UTC, JonasKellerer commented on components/package.json
>          ".": {
Good idea. This way one does not mix them up.

2024-11-21 08:05 UTC, fengelniederhammer commented on components/vite.release-standalone.config.ts
> +                'dashboard-components': 'dist/components.js',
This only contains the components then, doesn't it? It doesn't contain the util stuff? Do we need a separate entry point, if we want to provide both?

2024-11-21 08:05 UTC, fengelniederhammer commented on components/README.md
> +We also provide utility functions for usage with our components, which can also be used in a node environment.
Do we want to add a test that it can be used in a node environment? How hard would that be?

2024-11-21 08:07 UTC, fengelniederhammer commented
I think we should also adapt the breaking changes message to something like "components: the web components must now be imported from `...components.js`,  `DateRangeOption` and `dateRangeOptionPresets` must be imported from ..."

2024-11-21 08:34 UTC, JonasKellerer commented on components/vite.release-standalone.config.ts
> +                'dashboard-components': 'dist/components.js',
Good catch. 
As discussed: we now have a `standaloneEntypoint.ts` file, which exports everything.

2024-11-21 09:01 UTC, JonasKellerer commented on components/README.md
> +We also provide utility functions for usage with our components, which can also be used in a node environment.
As discussed: we will postpone this, when we have a good idea.
I have created a ticket to keep track of this: #534

2024-11-21 13:00 UTC, merged